### ISSUE TITLE
Missing `--ignore-src` Flag

### ISSUE THREAD

**Issue by muttistefano** [ichiro-its/ros2-ws-action#4]
Hi all,
how do i call rosdep prior to the build ? 
Thanks

**Comment by muttistefano** [comment]
My bad, rosdep is called already.
My problem is due to the fact that meta-packages wont find packages included in themselves, and throw an error.
This should be due by the fact that rosdep is called without the "--ignore-src" flag.
Is there a reason this flag is missing ? 
Thanks

**Comment by threeal** [comment]
There's no reason, do you want us to add an option to allows adding that flag?

**Comment by muttistefano** [comment]
Hi, thanks for the answer.
I there should be no cases in which that flag creates problems.
Thanks
